In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#loading the dataset
train=pd.read_csv("/content/SalaryData_Train(1).csv")

In [ ]:
test=pd.read_csv("/content/SalaryData_Test(1).csv")

In [ ]:
train

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30156,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
30157,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
30158,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
30159,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
30160,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
test

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,Private,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K
15056,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K
15057,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
15058,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K
15059,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K

In [ ]:
#EDA
train["occupation"].unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Transport-moving',
       ' Farming-fishing', ' Machine-op-inspct', ' Tech-support',
       ' Craft-repair', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64
 10  capitalloss    30161 non-null  int64
 11  hoursperweek   30161 non-null  int64
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            15060 non-null  int64
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64
 10  capitalloss    15060 non-null  int64
 11  hoursperweek   15060 non-null  int64
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB

In [ ]:
train.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [ ]:
test.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [ ]:
#as we dont have any null values in the datasets we can go to next step
#and we dont need scaling as we the dataset is in a categorical manner

In [ ]:
#performing label encoding for the above datasets

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le= LabelEncoder()

In [ ]:
train["workclass"]=le.fit_transform(train["workclass"])

In [ ]:
train["education"]=le.fit_transform(train["education"])

In [ ]:
train["occupation"]=le.fit_transform(train["occupation"])

In [ ]:
train["sex"]=le.fit_transform(train["sex"])

In [ ]:
train["native"]=le.fit_transform(train["native"])

In [ ]:
test["workclass"]=le.fit_transform(test["workclass"])

In [ ]:
test["education"]=le.fit_transform(test["education"])

In [ ]:
test["occupation"]=le.fit_transform(test["occupation"])

In [ ]:
test["sex"]=le.fit_transform(test["sex"])

In [ ]:
test["native"]=le.fit_transform(test["native"])

In [ ]:
train["Salary"]=le.fit_transform(train["Salary"])

In [ ]:
test["Salary"]=le.fit_transform(test["Salary"])

In [ ]:
train

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,5,9,13,Never-married,0,Not-in-family,White,1,2174,0,40,37,0
1,50,4,9,13,Married-civ-spouse,3,Husband,White,1,0,0,13,37,0
2,38,2,11,9,Divorced,5,Not-in-family,White,1,0,0,40,37,0
3,53,2,1,7,Married-civ-spouse,5,Husband,Black,1,0,0,40,37,0
4,28,2,9,13,Married-civ-spouse,9,Wife,Black,0,0,0,40,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30156,27,2,7,12,Married-civ-spouse,12,Wife,White,0,0,0,38,37,0
30157,40,2,11,9,Married-civ-spouse,6,Husband,White,1,0,0,40,37,1
30158,58,2,11,9,Widowed,0,Unmarried,White,0,0,0,40,37,0
30159,22,2,11,9,Never-married,0,Own-child,White,1,0,0,20,37,0
30160,52,3,11,9,Married-civ-spouse,3,Wife,White,0,15024,0,40,37,1

In [ ]:
test

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,2,1,7,Never-married,6,Own-child,Black,1,0,0,40,37,0
1,38,2,11,9,Married-civ-spouse,4,Husband,White,1,0,0,50,37,0
2,28,1,7,12,Married-civ-spouse,10,Husband,White,1,0,0,40,37,1
3,44,2,15,10,Married-civ-spouse,6,Husband,Black,1,7688,0,40,37,1
4,34,2,0,6,Never-married,7,Not-in-family,White,1,0,0,30,37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,2,9,13,Never-married,9,Own-child,White,1,0,0,40,37,0
15056,39,2,9,13,Divorced,9,Not-in-family,White,0,0,0,36,37,0
15057,38,2,9,13,Married-civ-spouse,9,Husband,White,1,0,0,50,37,0
15058,44,2,9,13,Divorced,0,Own-child,Asian-Pac-Islander,1,5455,0,40,37,0
15059,35,3,9,13,Married-civ-spouse,3,Husband,White,1,0,0,60,37,1

In [ ]:
#dropping the unwanted columns

In [ ]:
train.drop(columns=["maritalstatus","relationship","race"],inplace=True)

In [ ]:
test.drop(columns=["maritalstatus","relationship","race"],inplace= True)

In [ ]:
#creating the model
model= SVC(kernel="rbf",C=12)

In [ ]:
#splitting to xtrain,xtest,ytrain,ytest

In [ ]:
xtrain= train.iloc[:,:-1]
ytrain= train.iloc[:,-1]

In [ ]:
xtest = test.iloc[:,:-1]
ytest = test.iloc[:,-1]

In [ ]:
#fitting the model

In [ ]:
model.fit(xtrain,ytrain)

SVC(C=12)

In [ ]:
#making predictions using xtest
ypred = model.predict(xtest)

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.80      0.98      0.88     11360
           1       0.80      0.26      0.39      3700

    accuracy                           0.80     15060
   macro avg       0.80      0.62      0.64     15060
weighted avg       0.80      0.80      0.76     15060

In [ ]:
model.score(xtrain,ytrain)

0.8030900832200524

In [ ]:
#accuracy using cross_val_score

In [ ]:
from sklearn.model_selection import cross_val_score
cvs= cross_val_score(model,xtrain,ytrain,cv=10)

In [ ]:
#visualization

FORESTFIRES DATASET

In [ ]:
#loading the dataset

In [ ]:
df=pd.read_csv("forestfires.csv")

In [ ]:
df

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,large
513,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,large
514,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,large
515,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,small
516,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,1,0,0,small

In [ ]:
#encoding the data using labelencoder as le
df["month"]=le.fit_transform(df["month"])
df["day"]=le.fit_transform(df["day"])

In [ ]:
df["size_category"]=le.fit_transform(df["size_category"])

In [ ]:
df

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,7,0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,1
1,10,5,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,1
2,10,2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,1
3,7,0,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,1
4,7,3,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,1,3,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,0
513,1,3,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,0
514,1,3,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,0
515,1,2,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,1
516,9,5,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,1,0,0,1

In [ ]:
#independent and dependent variable
x1 = df.iloc[:,:-1]
y1 = df.iloc[:,-1]

In [ ]:
x1

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
0,7,0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,0,1,0,0,0,0
1,10,5,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,0,1,0
2,10,2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,0,1,0
3,7,0,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,0,1,0,0,0,0
4,7,3,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,1,3,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,0
513,1,3,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,0
514,1,3,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,0
515,1,2,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,0
516,9,5,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
#scaling the data using standardscaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x1=sc.fit_transform(x1)

In [ ]:
x1

array([[ 2.84222252e-01, -1.42312073e+00, -8.05959472e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [ 9.70871338e-01,  1.17671466e+00, -8.10203395e-03, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       [ 9.70871338e-01, -3.83186570e-01, -8.10203395e-03, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       ...,
       [-1.08907592e+00,  1.36780508e-01, -1.64008316e+00, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-1.08907592e+00, -3.83186570e-01,  6.80956663e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [ 7.41988309e-01,  1.17671466e+00, -2.02087875e+00, ...,
         2.27156334e+01, -1.72859706e-01, -7.06081245e-01]])

In [ ]:
#model
model1= SVC(kernel="rbf",C=15)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain1,xtest1,ytrain1,ytest1=train_test_split(x1,y1,test_size=0.2,random_state=250)

In [ ]:
model1.fit(xtrain1,ytrain1)

SVC(C=15)

In [ ]:
ypred1= model1.predict(xtest1)

In [ ]:
print(classification_report(ytest1,ypred1))

              precision    recall  f1-score   support

           0       0.81      0.65      0.72        26
           1       0.89      0.95      0.92        78

    accuracy                           0.88       104
   macro avg       0.85      0.80      0.82       104
weighted avg       0.87      0.88      0.87       104

In [ ]:
#accuracy using cross_val_score

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
res= cross_val_score(model1,x1,y1,cv=15)

In [ ]:
res.mean()

0.8236974789915968

In [ ]:
res

array([0.8       , 0.74285714, 0.8       , 0.91428571, 0.94285714,
       0.91428571, 0.8       , 0.88235294, 0.70588235, 0.82352941,
       0.82352941, 0.82352941, 0.76470588, 0.79411765, 0.82352941])